twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
# _errors:
#     resource: '@TwigBundle/Resources/config/routing/errors.xml'
#     prefix:   /_error    